require 'json'
require 'rest_client'
require 'badgeville/error'
require 'badgeville/helpers'
require 'badgeville/activity'
require 'badgeville/reward'
require 'badgeville/version'
require 'badgeville/client'
